language: node_js

node_js:
  - "iojs"

sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - bash build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master

# script:
#   - bash build.sh
# after_success:
#   - bash deploy.sh
# env:
#   global:
#   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
